config/routes.rb
Smartfarm::Application.routes.draw do
  resources :soils

  resources :simulations
  
  resources :references

  resources :farms
  get 'tags/:tag', to: 'farms#index', as: :tag

  resources :weather

  resources :crops 
  post '/crops/:id' => 'crops#update'

  devise_for :users
  resources :users

  post '/generate_list/csv' => 'generate_list#csv'

  root 'welcome#index'

end

app/models/simulation.rb
class Simulation < ActiveRecord::Base
  has_paper_trail
  belongs_to :user
  belongs_to :farm
  belongs_to :weather
  belongs_to :soil
  validates_presence_of :name, :start_on, :end_on 
  validates_presence_of :farm_id, message: "must be selected"
  validates_presence_of :weather_id, message: "must be selected"
  validates_presence_of :soil_id, message: "must be selected"
end

app/controllers/simulations_controller.rb
class SimulationsController < InheritedResources::Base
  respond_to :js, only: [:show]
  respond_to :json, only: [:show]
  
	before_filter :must_be_owner_or_member_or_admin, only: [:destroy]
	def must_be_owner  
		if current_user == nil
			redirect_to root_url, notice: "You are not signed in."
		elsif Simulation.find(params[:id]).user.id != current_user.id
			redirect_to @project, notice: "You do not have privileges to delete this record."
		end
	end

  def index
    @simulations = Simulation.page
    index!
  end
  
  def new
    @simulation = Simulation.new
    @farms = Farm.page
    @weather = Weather.page
    @soils = Soil.page
    new!
  end

  def show
    @simulation = Simulation.find(params[:id])
    @crops = Crop.page
    show!
  end

  def create
    @simulation = Simulation.new(resource_params)
    @simulation.user = current_user
    @farms = Farm.page
    @weather = Weather.page
    @soils = Soil.page
    create!
  end

  def edit
	# Edit or create copy to edit (if not owner)
	if Simulation.find(params[:id]).user.id != current_user.id
		@simulation = Simulation.find(params[:id]).dup
		@simulation.user = current_user
	else
		@simulation = Simulation.find(params[:id])
	end
	@farms = Farm.page
	@weather = Weather.page
	@soils = Soil.page
	@crops = Crop.page 
	edit!
  end

private

  def resource_params
    params.require(:simulation).permit(:name, :start_on, :end_on, :description, :farm_id, :weather_id, :soil_id, :state)
  end

end

app/helpers/simulations_helper.rb
module SimulationsHelper
end

app/views/simulations/_crop_select.html.erb
<!-- crop select modal -->
<div id="crop-select-modal" class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labeled-by="cropSelectionLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="cropSelectionLabel">Crop Selection</h4>
      </div>
      <div class="modal-body">
        <p>
           Which crop do you want to plant?
        </p>
        <%= paginate @crops, remote: true, params: {controller: :crops, action: :index} %>
        <div id="crops" class="row">
          <%= render @crops %>
        </div>
        <%= paginate @crops, remote: true, params: {controller: :crops, action: :index} %>
      </div>
      <div class="modal-footer">
        <input type="hidden" name="crop_id" value="-1" >
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button id="crop-select-modal-ok" type="button" class="btn btn-default" data-dismiss="modal">Ok</button>
      </div>
    </div>
  </div>
</div>

app/views/simulations/_details.html.erb
<div class="row">

  <div class="col-sm-4">
    <canvas id="thumb" width=250 height=200>
  </div>

  <div class="col-sm-8">

     <div class="form_group">
       <%= f.label :name %>
       <%= f.text_field :name, class: "form-control" %>
     </div>

     <div class="form_group">
       <%= f.label :start_on %>
       <%= f.date_field :start_on, class: "form-control" %>
     </div>

     <div class="form_group">
        <%= f.label :end_on %>
        <%= f.date_field :end_on, class: "form-control" %>
     </div>

     <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, class: "form-control" %>
     </div>

  </div>

</div>

app/views/simulations/_farm.html.erb
<div class="bs-callout bs-callout-info">
  <h4>Picking your farm</h4>
  <p>
    Before you can run your simulation, you need to identify the characteristics of the farm
    you intend to simulate.  You can choose from all the farms that have been uploaded into
    the SmartFarm site, or you can <%= link_to 'create your own', new_farm_path %> and then
    come back to create your simulation.
  </p>
</div>

 <div class="row">
  <div class="col-md-4">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h4 class="panel-title">Farm to Simulate</h4>
      </div>
      <div id="selected-farm" class="panel-body">
        <%= render @simulation.farm if @simulation.farm %>
      </div>
    </div>
  </div>

   <div class="col-md-8">
      <h4>
        Farms
        <!--div class="btn-group">
          <button type="button" class="btn btn-success">My Farms</button>
          <button type="button" class="btn btn-default">All Farms</button>
        </div-->
      </h4>
      <div id="farm-pagination">
        <%= paginate @farms, remote: true, params: {controller: "farms", action: "index"} %>
      </div>
      <div id="unselected-farms">
        <%= render @farms %>
      </div>
  </div>
</div>

app/views/simulations/_field_select.html.erb
<!-- field select modal -->
<div id="field-select-modal" class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labeled-by="fieldSelectionLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="fieldSelectionLabel">Field Selection</h4>
      </div>
      <div class="modal-body">
        <div class="row">
          <div id="field-select-map" class="col-sm-8">
            <%= @simulation.farm.to_svg.html_safe %>
          </div>
          <div class="col-sm-4">
            <div class="btn-group-vertical" data-toggle="buttons">
            <% @simulation.farm.to_svg.scan(/polygon/).length.times do |index| %>
              <label class="btn btn-default">
                <input name="field_id" type="radio" value="<%= index %>">Field <%= index %>
              </label>
            <% end %>
            </div>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <div class="btn-group" data-toggle="buttons">
          <label class="btn btn-default" data-dismiss="modal">
            <input name="field_id" type="radio" value="-1">Cancel
          </label>
        </div>
        <button type="button" class="btn btn-default" data-dismiss="modal">Ok</button>
      </div>
    </div>
  </div>
</div>

app/views/simulations/_form.html.erb
<% unless @simulation.errors.empty? %>
  <div class="alert alert-danger">
  <% @simulation.errors.full_messages.each do |msg| %>
    <p><%= msg %></p>
  <% end %>
  </div>
<% end %>

<%= form_for(@simulation, html: {id: "simulation-form", class: "simulation-form"}) do |f| %>

  <button id="save" type="submit" role="button" class="pull-right btn-success"><i class="fa fa-floppy-o"></i></button>

  <ul class="nav nav-tabs">
    <li class="active"><a href="#details" data-toggle="tab">Details</a></li>
    <li><a href="#farm" data-toggle="tab">Farm</a></li>
    <li><a href="#weather" data-toggle="tab">Weather</a></li>
    <li><a href="#soil" data-toggle="tab">Soil</a></li>
  </ul>


  <div class="tab-content">

    <div class="tab-pane active" id="details">
      <%= render partial: "details", locals: {f: f} %>
    </div>

    <div class="tab-pane" id="farm">
      <%= render "farm" %>
    </div>

    <div class="tab-pane" id="weather">
      <%= render "weather" %>
    </div>

    <div class="tab-pane" id="soil">
      <%= render "soil" %>
    </div>

  </div>

  <%= f.hidden_field :state %>
  <%= f.hidden_field :farm_id %>
  <%= f.hidden_field :weather_id %>
  <%= f.hidden_field :soil_id %>

<% end %>

      
<%= link_to 'Back', simulations_path %>

app/views/simulations/_liang_barsky.js.erb
//
// This routine uses the Liang-Barsky algorithm for polygon clipping as
// desribed in Foley & van Dam.  It's more efficient than the above
// Sutherland-Hodgman, but produces redundent turning vertices at the
// corners of the clip region.  This makes rendering as a series of
// triangles very awkward.
//

var INFINITY = 2147483647;

function clipPolygon(sourcePoly, clipRect) {
  var xIn, xOut, yIn, yOut,          // Coordinates of entry and exit points
    tOut1, tIn2, tOut2,            // Parameter values of same
    tInX, tOutX, tInY, tOutY,      // Parameter values for intersection
    deltaX, deltaY;                // Direction of edge

  var clippedPoly = []
  var copiedPoly = sourcePoly.map( function(vertex) { // Shallow copy of source
    return {x: vertex.x, y: vertex.y}
  });
  copiedPoly.push({x: sourcePoly[0].x, y: sourcePoly[0].y}); // Close polygon

  for(var i = 0; i < sourcePoly.length; i++) {  // for each edge 

    deltaX = copiedPoly[i+1].x - copiedPoly[i].x;  // determine direction of edge
    deltaY = copiedPoly[i+1].y - copiedPoly[i].y;  

    // use this to determine which bounding lines for the clip region the
    // containing line hits first
    if((deltaX > 0) || (deltaX == 0 && copiedPoly[i].x > clipRect.right)) {
      xIn = clipRect.left; xOut = clipRect.right;
    } else {
      xIn = clipRect.right; xOut = clipRect.left;
    }
    if((deltaY > 0) || (deltaY == 0 && copiedPoly[i].y > clipRect.bottom)) {
      yIn = clipRect.top; yOut = clipRect.bottom;
    } else {
      yIn = clipRect.bottom; yOut = clipRect.top;
    }

    // find the t values for the x and y exit points
    if(deltaX != 0) {
      tOutX = ((xOut - copiedPoly[i].x)<<8) / deltaX;
    } else if(copiedPoly[i].x <= clipRect.right && clipRect.left <= copiedPoly[i].x)
      tOutX = INFINITY;
    else
      tOutX = -INFINITY;

    if(deltaY != 0) {
      tOutY = ((yOut - copiedPoly[i].y)<<8) / deltaY;
    } else if(copiedPoly[i].y <= clipRect.bottom && clipRect.top <= copiedPoly[i].y)
      tOutY = INFINITY;
    else
      tOutY = -INFINITY;

    // Order the two exit points
    if(tOutX < tOutY) {
      tOut1 = tOutX; tOut2 = tOutY;
    } else {
      tOut1 = tOutY; tOut2 = tOutX;
    }

    if(tOut2 > 0) {

      if(deltaX != 0)
        tInX = ((xIn - copiedPoly[i].x)<<8) / deltaX;
      else
        tInX = -INFINITY;

      if(deltaY != 0)
        tInY = ((yIn - copiedPoly[i].y)<<8) / deltaY;
      else
        tInY = -INFINITY;

      if(tInX < tInY)
        tIn2 = tInY;
      else
        tIn2 = tInX;

      if(tOut1 < tIn2) {  // no visible segment
        if(0 < tOut1 && tOut1 <= (1<<8)) {
          // line crosses over intermediate corner region
          if(tInX < tInY) {
            clippedPoly.push({
              x: xOut,
              y: yIn
            });
          } else {
            clippedPoly.push({
              x: xIn,
              y: yOut
            });
          }
        }
      } else {

        // line crosses though window
        if(0 < tOut1 && tIn2 <= (1<<8)) {
          if(0 <= tIn2) {  // visible segment
            if(tInX > tInY) {
              clippedPoly.push({
                x: xIn,
                y: copiedPoly[i].y + ((tInX * deltaY)>>8)
              });
            } else {
              clippedPoly.push({
                x: copiedPoly[i].x + ((tInY * deltaX)>>8),
                y: yIn
              });
            }
          }

          if((1<<8) >= tOut1) {
            if(tOutX < tOutY) {
              clippedPoly.push({
                x: xOut,
                y: copiedPoly[i].y + ((tOutX * deltaY)>>8)
              });
            } else {
              clippedPoly.push({
                x: copiedPoly[i].x + ((tOutY * deltaX)>>8),
                y: yOut
              });
            }
          } else {
            clippedPoly.push({
              x: copiedPoly[i+1].x,
              y: copiedPoly[i+1].y
            });
          }
        }

      }

      if(0 < tOut2 && tOut2 <= (1<<8)) {
        clippedPoly.push({
        x: xOut,
        y: yOut
        });
      }

    }
  } 

  return clippedPoly;
}

app/views/simulations/_load_via_xhr.js.erb
function load(url, callback) {
	var xhr;
 
	if(typeof XMLHttpRequest !== 'undefined') xhr = new XMLHttpRequest();
	else {
		var versions = ["MSXML2.XmlHttp.5.0", 
			 	"MSXML2.XmlHttp.4.0",
			 	"MSXML2.XmlHttp.3.0", 
			 	"MSXML2.XmlHttp.2.0",
			 	"Microsoft.XmlHttp"]
 
		for(var i = 0, len = versions.length; i < len; i++) {
		try {
			xhr = new ActiveXObject(versions[i]);
			break;
		}
			catch(e){}
		} // end for
	}
		
	xhr.onreadystatechange = ensureReadiness;
		
	function ensureReadiness() {
		if(xhr.readyState < 4) {
			return;
		}
			
		if(xhr.status !== 200) {
			return;
		}
 
		// all is well	
		if(xhr.readyState === 4) {
			callback(xhr);
		}			
	}
		
	xhr.open('GET', url, true);
	xhr.send('');
}

app/views/simulations/_simulation.html.erb
<div class="thumbnail simulation" data-id="<%= simulation.id %>">
  <%= link_to simulation do %>
    <%= simulation.farm.to_svg.html_safe %>
    <strong><%= simulation.name %></strong>
  <% end %>
  <p>by <%= link_to simulation.user.username, simulation.user %></p>
</div>

app/views/simulations/_soil.html.erb
<div class="bs-callout bs-callout-info">
  <h4>Picking your soil model</h4>
  <p>
    Before you can run your simulation, you need to identify the soil model you wish to use
    within your simulation.  You can choose from all the soil models that have been uploaded 
    into the SmartFarm site, or you can <%= link_to 'create your own', new_soil_path %> and then
    come back to create your simulation.
  </p>
</div>

 <div class="row">
  <div class="col-md-4">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h4 class="panel-title">Soil model to use</h4>
      </div>
      <div id="selected-soil" class="panel-body">
        <%= render @simulation.soil if @simulation.soil %>
      </div>
    </div>
  </div>

   <div class="col-md-8">
      <h4>
        Soils
        <!--div class="btn-group">
          <button type="button" class="btn btn-success">My Soil Models</button>
          <button type="button" class="btn btn-default">All Soil Models</button>
        </div-->
      </h4>
      <div id="soil-pagination">
        <%= paginate @soils, remote: true, params: {controller: 'soils', action: 'index'} %>
      </div>
      <div id="unselected-soils">
        <%= render @soils %>
      </div>
  </div>
</div>

app/views/simulations/_weather.html.erb
<div class="bs-callout bs-callout-info">
  <h4>Picking your weather model</h4>
  <p>
    Before you can run your simulation, you need to identify the model by which you will
    simulate weather.  You can choose form all the weather models that have been uploaded
    into the SmartFarm site, or you can <%= link_to 'create your own', new_weather_path %>
    and then come back to create your simulation.
  </p>
</div>

 <div class="row">
  <div class="col-md-4">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h4 class="panel-title">Weather Model to Use</h4>
      </div>
      <div id="selected-weather" class="panel-body">
        <%= render @simulation.weather if @simulation.weather %>
      </div>
    </div>
  </div>

   <div class="col-md-8">
      <h4>
        Weather
        <!--div class="btn-group">
          <button type="button" class="btn btn-success">My Weather Models</button>
          <button type="button" class="btn btn-default">All Weather Models</button>
        </div-->
      </h4>
      <div id="weather-pagination">
        <%= paginate @weather, remote: true, params: {controller: "weather", action: "index"} %>
      </div>
      <div id="unselected-weather">
        <%= render @weather %>
      </div>
  </div>
</div>

app/views/simulations/edit.html.erb
<h1>Editing simulation</h1>

<%= render 'form' %>

<%= link_to 'Show', @simulation %> |
<%= link_to 'Back', simulations_path %>

app/views/simulations/new.html.erb
<h1>New Simulation</h1>

<%= render "form" %>

app/views/simulations/show.html.erb
<div class="well">

  <div id="simulation-controls" class="row">

    <div id="simulation-calendar" class="pull-left">
      <div id="calendar-month">
        <%= @simulation.start_on.strftime("%b") %>
      </div>
      <div id="calendar-day">
        <%= @simulation.start_on.day %>
      </div>
    </div>

    <div id="simulation-clock" class="pull-left">
      <%= @simulation.start_on.strftime("%H:%M") %>
    </div>

    <button id="simulation-run" role="button" class="btn">
      <i class="fa fa-play"></i> Run
    </button>

    <button id="simulation-pause" role="button" class="btn">
      <i class="fa fa-pause"></i> Pause
    </button>

    <button id="simulation-restart" role="button" class="btn">
      <i class="fa fa-refresh"></i> Restart
    </button>

    <a id="edit" href="<%= edit_simulation_path(@simulation) %>" role="button" class="btn btn-info pull-right"> 
      <i class="fa fa-edit"></i> Edit
    </a>

  </div>

</div>

<ul class="nav nav-tabs">
  <li class="active"><a href="#farm" data-toggle="tab">Farm Operations</a></li>
  <li><a href="#details" data-toggle="tab">Details</a></li>
  <li><a href="#soil-data" data-toggle="tab">Soil Data</a></li>
  <li><a href="#crop-data" data-toggle="tab">Crop Data</a></li>
</ul>

<div class="tab-content">
  
  <div class="tab-pane active" id="farm">
    <div class="row">

      <div class="col-md-1 simulation-buttons-wrapper">
		<div class="button-group-vertical button-manual">
			<div class="button-group-label">Master Controls</div>
			<button id="field-select" class="simulation-button" role="button">Select Field</button>
			<button id="toggle-granularity" class="simulation-button" role="button">Show Patches</button>
			<button id="clear-game-path" class="simulation-button" role="button">Cancel Navigation</button>
		</div>
        <div class="button-group-vertical button-manual">
          <div class="button-group-label">Manual</div>
          <button id="manual-till" class="simulation-button" role="button">Manual Till</button>
          <button id="manual-plant" class="simulation-button" role="button">Manual Plant</button>
          <button id="manual-harvest" class="simulation-button" role="button">Manual Harvest</button>
        </div>
        <div class="button-group-vertical button-auto">
          <div class="button-group-label">Automatic</div>
          <button id="auto-till" class="simulation-button" role="button">Auto Till</button>
          <button id="auto-plant" class="simulation-button" role="button">Auto Plant</button> 
          <button id="auto-harvest" class="simulation-button" role="button">Auto Harvest</button>
        </div>
		
		
		<!-- TEMP !!!
		<div class="button-group-vertical button-auto">
          <button id="draw-granularity" class="simulation-button" role="button">Draw Granularity</button>
		  <label><input type="checkbox" id="draw-granularity" style="position:relative; top:2px; margin-right: 5px;"> Show Granularity</label>
        </div> -->
		
		
		<div class="button-group-vertical button-auto">
			<div id="viewport-div" class="button-group-label">Viewport</div>
			<table id="simulation-pan-arrow-menu">
				<tr>
					<td>
					</td>
					<td>
						<button id="simulation-pan-up" role="button" class="btn pan-viewport-btn">
							&#8593;
						</button>
					</td>
					<td>
					</td>
				</tr>
				<tr>
					<td>
						<button id="simulation-pan-left" role="button" class="btn pan-viewport-btn">
							&#8592;
						</button>
					</td>
					<td>
						<button id="simulation-pan-center" role="button" class="btn pan-viewport-btn">
							<%= image_tag("tractor.png", :alt => "center", :class => "") %>
						</button>
					</td>
					<td>
						<button id="simulation-pan-right" role="button" class="btn pan-viewport-btn">
							&#8594;
						</button>
					</td>
				</tr>
				<tr>
					<td>
					</td>
					<td>
						<button id="simulation-pan-down" role="button" class="btn pan-viewport-btn">
							&#8595;
						</button>
					</td>
					<td>
					</td>
				</tr>
			</table>
		</div>
		<button id="simulation-expand-viewport-button" role="button" class="simulation-button">Expand Viewport</button>
		<button id="simulation-shrink-viewport-button" role="button" class="simulation-button">Shrink Viewport</button>
		
		
      </div>

      <div class="col-md-11 simulation-box-wrapper">
		<div id="farm-display"></div>
      </div>

    </div>
  </div>

  <div class="tab-pane" id="details">
<p>
  <strong>Name:</strong>
  <%= @simulation.name %>
</p>

<p>
  <strong>Start on:</strong>
  <%= @simulation.start_on %>
</p>

<p>
  <strong>End on:</strong>
  <%= @simulation.end_on %>
</p>

<p>
  <strong>Description:</strong>
  <%= @simulation.description %>
</p>

  </div>

  <div class="tab-pane" id="soil-data">
    <div class="row">
      <div class="col-md-2">
        <div id="soil-data-layer-checkboxes">
          <h4>Legend</h4>
        </div>
      </div>
      <div class="col-md-10">
        <div id="soil-data-layers" class="data-layers">
        </div>
      </div>
    </div>
  </div>

  <div class="tab-pane" id="crop-data">
    <div class="row">
      <div class="col-md-2">
        <div id="crop-data-layer-checkboxes">
          <h4>Legend</h4>
        </div>
      </div>
      <div class="col-md-10">
        <div id="crop-data-layers" class="data-layers">
        </div>
      </div>
    </div>
  </div>

</div>

<p>
  <strong>User:</strong>
  <%= @simulation.user_id %>
</p>


<%= link_to 'Edit', edit_simulation_path(@simulation) %> |
<%= link_to 'Back', simulations_path %>

<%= render "field_select" %>
<%= render "crop_select" %>