config/routes.rb
Smartfarm::Application.routes.draw do
  resources :soils

  resources :simulations
  
  resources :references

  resources :farms
  get 'tags/:tag', to: 'farms#index', as: :tag

  resources :weather

  resources :crops 
  post '/crops/:id' => 'crops#update'

  devise_for :users
  resources :users

  post '/generate_list/csv' => 'generate_list#csv'

  root 'welcome#index'

end

app/models/farm.rb
class Farm < ActiveRecord::Base
  has_paper_trail
  acts_as_taggable

  belongs_to :user

  validates_presence_of :user, :name, :latitude, :longitude, :data

  def to_svg
    @svg ||= generate_svg
  end

  def static_map_url
    bounds = JSON.parse(data)["field_bounds"] || []
    bounds.reject!(&:empty?)
    paths = bounds.collect do |field| 
      "path=color:0x000000ff|#{(field.collect{ |corner| "#{ corner["latitude"] },#{ corner["longitude"] }"} + ["#{field[0]["latitude"]},#{field[0]["longitude"]}"] ).join("|") }".html_safe
    end
    args = ["http://maps.googleapis.com/maps/api/staticmap?", #key=AIzaSyAWk3UQFfLP1-q-VrLd46sKcZ-RyYMDfTM",
       "markers=color:red|#{latitude},#{longitude}",
       "zoom=13",
       "maptype=terrain",
       "size=600x300"
      ]
     (args + paths).join("&")
  end



private

  def generate_svg
    width = 300
    height = 200
    svg = "<svg viewbox='0 0 #{width} #{height}'>"

    farm_data = JSON.parse data
    north = farm_data["location"]["latitude"]
    south = farm_data["location"]["latitude"]
    east = farm_data["location"]["longitude"]
    west = farm_data["location"]["longitude"]

    if farm_data["field_bounds"]

      # Find the outer boundaries of the simulation
      for bound in farm_data["field_bounds"]
        for corner in bound
          north = corner["latitude"] > north ? corner["latitude"] : north;
          south = corner["latitude"] < south ? corner["latitude"] : south;
          west = corner["longitude"] > west ? corner["longitude"] : west;
          east = corner["longitude"] < east ? corner["longitude"] : east;
        end
      end

      # Convert field bounds into pixel coordinates
      farm_data["field_bounds"].each_with_index do |bound, index|
        points = []
        left = width
        right = 0
        top = 0
        bottom = height
        for corner in bound
          x = (corner["longitude"] - east) * (width / (west - east))
          y = height - (corner["latitude"] - south) * (height / (north - south))
          left = x < left ? x : left
          right = x > right ? x : right
          top = y > top ? y : top
          bottom = y < bottom ? y : bottom
          points << "#{x},#{y}"
        end
        svg << "<polygon data-field-index='#{ index }' points='#{ points.join(" ") }' style='stroke:black;stroke-width:5' />"
        svg << "<text x='#{left + ((right - left) / 2)}' y='#{bottom + ((top - bottom) / 2)}' font-family='Veranda' font-size='55'>#{ index }</text>"
      end
    end
    svg << "</svg>"
  end

end

app/controllers/farms_controller.rb
class FarmsController < InheritedResources::Base
  respond_to :js, only: [:index, :delete]
  respond_to :json, only: :show

  def index
	if params[:tag]
		@farms = Farm.tagged_with(params[:tag]).page params[:page]
		index!
	else
		@farms = Farm.page params[:page]
		index!
	end
  end

  def create
    @farm = Farm.new(resource_params)
    @farm.user = current_user
    create!
  end

  def new
    @farm = Farm.create(
      user: current_user, 
      name: "Unnamed farm", 
      latitude: 39.1974437, 
      longitude: -96.5847248999, 
      data: '{"name":"Unnamed farm", "location": {"latitude": 39.1974437, "longitude": -96.5847248999}, "field_bounds": [], "elevation_samples": [], "soil_samples": []}'
    )
#    render :edit
  end

  def update
	
    #Create a clone if we aren't the owner
	if Farm.find(params[:id]).user.id != current_user.id
		@farm = Farm.find(params[:id]).dup
		@farm.user = current_user
	else
		@farm = Farm.find(params[:id])
	end
	update!
  end

  def destroy
	@farm = Farm.find(params[:id])
	@farm.destroy
  end

private

  def resource_params
    params.require(:farm).permit(:name, :latitude, :longitude, :description, :data, :tag_list)
  end
  
end

app/helpers/farms_helper.rb
module FarmsHelper
end

app/views/farms/_boundary_corner.html.erb
<tr class="boundary-corner">
  <td class="field-index">
    A
  </td>
  <td class="corner-index">
    B
  </td>
  <td>
    <input type="number" step="any" class="latitude">
  </td>
  <td>
    <input type="number" step="any" class="longitude">
  </td>
  <td>
     <button class="btn btn-xs btn-danger remove"><i class="fa fa-o-cross"></i> Remove</button>
  </td>
</tr>

app/views/farms/_elevation.html.erb
<div class="bs-callout bs-callout-info">
  <h4>Establishing your farm's elevation</h4>
  <p>
    You need to provide your farm's elevation. This can be done by clicking on the specific locations of elevation measurements in the map below, 
    and then manually entering the elevation measures.  You can also manually create the elevation points with the "Add Elevation Marker" button.  
    Alternatively, if your device has equipped GPS, you can use it to capture location (and possibly elevation) data with the "Use Device Position"
    button, after physically moving to where you wish to take an elevation measurement.
  </p>
</div>

<div id="farm_elevation_map"></div>

<table class="table">
  <theader>
    <tr>
      <th>Marker</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Elevation</th>
    </tr>
  </theader>
  <tbody id="elevation-samples">
  </tbody>
</table>

<button id="add-elevation-sample" type="button" class="btn btn-default" data-char="A" data-content='<%= render partial: "elevation_sample" %>'>Add Elevation Marker</button>

<button id="capture-elevation-sample" type="button" class="btn btn-default">Use Device Position</button>

app/views/farms/_elevation_sample.html.erb
<tr class="elevation-sample">
  <td>A</th>
  <td>
    <input type="number" step="any" class="latitude">
  </td>
  <td>
    <input type="number" step="any" class="longitude">
  </td>
  <td>
    <input type="number" step="any" class="elevation">
  </td>
  <td>
    <button type="button" class="btn btn-danger remove">&times; Remove</button>
  </td>
</tr>

app/views/farms/_farm.html.erb
<%= div_for farm, class: "thumbnail", data: {id: farm.id} do %>
  <%= link_to farm do %>
    <img src="<%= farm.static_map_url %>" alt="<%= farm.name %>" >
    <strong><%= farm.name %></strong>
  <% end %>
  <%= link_to('&times; Remove'.html_safe, farm, method: :delete, remote: true, confirm: "Are you sure you want to delete #{farm.name}?", class: "btn btn-danger btn-sm pull-right") if can? :delete, farm %>
  <p>by <%= link_to farm.user.username, farm.user %></p>

	<div>
		<%= raw farm.tag_counts_on(:tags).limit(@maxTagsShownPerFarm).map { |t| link_to t, tag_path(t.name), class: "tagClass" }.join(', ') %>
		<% if farm.tag_counts.count() > @maxTagsShownPerFarm %>
			<%= link_to "...", farm %>
		<% end %>
	</div>
<% end %>

app/views/farms/_field_boundaries.html.erb
<div class="bs-callout bs-callout-info">
  <h4>Establishing your farm's field boundaries</h4>
  <p>
    You need to provide the bounds of your farm. This can be done by clicking along the edges
    of the field in the map below.  To finish a field, click on the first point.  You can then 
    begin a new field.

    Switch to the hand tool to move existing points or fields.
  </p>
</div>

<div id="farm_field_map"></div>

<table class="table">                
  <thead>
    <tr>
      <th>Field</th>
      <th>Corner</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th></th>
    </tr>
  </thead>
  <tbody id="field-boundaries">
  </tbody>
</table>

<button id="begin-field" type="button" class="btn btn-default" data-index="1">Begin Field</button>

<button id="add-boundary-corner" type="button" class="btn btn-default" data-index="1" data-content='<%= render partial: "boundary_corner" %>'>Add Boundary Corner</button>

<button id="capture-boundary-corner" type="button" class="btn btn-default">Use Device Location</button>

app/views/farms/_form.html.erb
<%= form_for(@farm, html: {class: "farm-form"}) do |f| %>

  <button id="save" type="submit" role="button" class="pull-right btn-success"><i class="fa fa-floppy-o"></i></button>

  <ul class="nav nav-tabs">
    <li class="active"><a href="#details" data-toggle="tab">Details</a></li>
    <li><a id="location-tab" href="#location" data-toggle="tab">Location</a></li>
    <li><a id="boundary-tab" href="#boundary" data-toggle="tab">Field Boundaries</a></li>
    <li><a id="elevation-tab" href="#elevation" data-toggle="tab">Elevation</a></li>
    <li><a id="soil-tab" href="#soil" data-toggle="tab">Soil Profile</a></li>
  </ul>


  <div class="tab-content">

    <div class="tab-pane active" id="details">
      <div class="form_group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, class: "form-control" %>
      </div>
	  <div class="form-group">
		<%= f.label :tag_list, "Tags (separated by commas)" %><br>
		<%= f.text_field :tag_list, class: "form-control" %>
	  </div>
    </div>

    <div class="tab-pane" id="location">
      <%= render partial: "location", locals: {f: f} %>
    </div>

    <div class="tab-pane" id="boundary">
      <%= render partial: "field_boundaries", locals: {f: f} %>
    </div>

    <div class="tab-pane" id="elevation">
      <%= render partial: "elevation", locals: {f: f} %>
    </div>

    <div class="tab-pane" id="soil">
      <%= render partial: "soil_profile", locals: {f: f} %>
    </div>

  </div>

  <%= f.hidden_field :data %>

<% end %>

app/views/farms/_location.html.erb
      <div class="bs-callout bs-callout-info">
        <h4>Establishing your farm's location</h4>
        <p>
          You need to provide your farm's <a href="http://en.wikipedia.org/wiki/Geographic_coordinate_system">geographic coordinates<i class="fa fa-external-link"></i></a>.
          These can be provided three ways: 1) directly entering your farm's latitude and longitude, 2) searching by address, or 3) dragging the farm's pin to the
          appropriate location on the Google map.
        </p>
      </div>
      <div class="row">
        <div class="col-sm-4">
          <div class="form-group">
            <%= f.label :latitude %>
            <%= f.text_field :latitude, class: "form-control" %>
          </div>
        </div>
        <div class="col-sm-4">
          <div class="form-group">
            <%= f.label :longitude %>
            <%= f.text_field :longitude, class: "form-control" %>
          </div>
        </div>
        <div class="col-sm-1">
          <h3>OR</h3>
        </div>
        <div class="col-sm-3">
          <br/>
          <button id="capture-location" type="button" class="btn btn-default">Use Device Location</button>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-1">
          <h3>OR</h3>
        </div>
        <div class="col-sm-11">
          <div class="form-group">
            <%= label_tag "Search by Address" %>
            <div class="input-group">
              <%= text_field_tag :address, "", class: "form-control" %>
              <span class="input-group-btn">
                <button id="search-by-address" class="btn btn-default" type="button"><i class="fa fa-search"></i></button>
              </span>
            </div>
          </div>
        </div>        
      </div>
      <label>Drag on Map</label>
      <div id="farm-map"></div>

app/views/farms/_soil_profile.html.erb
<div class="bs-callout bs-callout-info">
  <h4>Establishing your farm's soil characteristics</h4>
  <p>
     You need to provide the soil profiles your farm.  You can click the map below to mark locations soil sample were taken, or manually
     enter the locations with the "Add Soil Sample" button.  Alternatively, if you have a GPS-enabled device the "Use Device Location" 
     button can be used mark the locations as you collect your soil samples.
  </p>
  <p>
    Once locations are marked, you need to enter the results of the soil sample test with the "Soil Properties" button for each row.
  </p>
</div>

<div id="farm_soil_profile_map"></div>

<table class="table">
  <theader>
    <tr>
      <th>Marker</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Properties</th>
    </tr>
  </theader>
  <tbody id="soil-samples">
  </tbody>
</table>

<button id="add-soil-sample" type="button" class="btn btn-default" data-char="A" data-content='<%= render partial: "soil_sample" %>'>Add Soil Sample</button>

<button id="capture-soil-sample" type="button" class="btn btn-default">Use Device Location</button>

app/views/farms/_soil_sample.html.erb
<tr class="soil-sample">
  <td>A</th>
  <td>
    <input type="number" step="any" class="latitude">
  </td>
  <td>
    <input type="number" step="any" class="longitude">
  </td>
  <td>
    <button type="button" class="btn btn-default" data-toggle="modal" data-target="#soil_properties_A">Soil Properties</button>
    <div id="soil_properties_A" class="modal fade">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
            <h4 class="modal-title">Soil Properties for Sample A</h4>
          </div>
          <div class="modal-body">
            <p>Enter the values for your soil sample below</p>
          <% for property in Soil::PROPERTIES %>
            <div class="form-group">
              <label class="control-label"><%= property.gsub('_', ' ') %></label>
              <input class="form-control" step="any" type="number" name="<%= property %>" class="<%= property %>">
            </div>
          <% end %>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>
  </td>
  <td>
    <button type="button" class="btn btn-danger remove">&times; Remove</button>
  </td>
</tr>

app/views/farms/destroy.js.erb
$('#farm_<%= @farm.id %>').remove()

app/views/farms/edit.html.erb
<%= render "form" %>

app/views/farms/index.js.erb
$('#unselected-farms').html('<%= escape_javascript render(@farms) %>');
$('#farm-pagination').html('<%= escape_javascript(paginate(@farms, remote: true)).to_s %>');
$('.farm a').on('click', function(event) {
  event.preventDefault();
  $('#selected-farm').children().detach().appendTo('#unselected-farms');
  selected_farm = $(this).parent().detach();
  selected_farm.detach().appendTo('#selected-farm');
  $('#simulation_farm_id').val( selected_farm.data('id') );
  return false;
});
$('.farm .btn').remove();

app/views/farms/new.html.erb
<h1>New farm</h1>

<%= render "form" %>

app/views/farms/show.json.erb
<%= @farm.data.html_safe %>