config/routes.rb
Smartfarm::Application.routes.draw do
  resources :soils

  resources :simulations
  
  resources :references

  resources :farms
  get 'tags/:tag', to: 'farms#index', as: :tag

  resources :weather

  resources :crops 
  post '/crops/:id' => 'crops#update'

  devise_for :users
  resources :users

  post '/generate_list/csv' => 'generate_list#csv'

  root 'welcome#index'

end

app/views/layouts/_import_data_dialog.html.erb
<!-- Import data file modal -->
<div class="modal fade" id="import-data-dialog" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title">Import Data File</h4>
      </div>
      <div class="modal-body">
        <p>ONE FINE DAY</p>
        <%= file_field_tag :data_file %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button id="import-data-button" type="button" class="btn btn-primary">Import</button>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<%= nav_bar fixed: :top, brand: "Smartfarm", brand_link: root_path, responsive: true do %>

    <%= menu_group do %>
       <%= menu_item "Simulations", simulations_path %>
       <%= menu_item "Farms", farms_path %>
       <%= menu_item "Soils", soils_path %>
       <%= menu_item "Crops", crops_path %>
       <%= menu_item "Weather", weather_index_path %>
       <%= menu_item "References", references_path %>
    <% end %>

    <%= menu_group pull: :right do %>
      <% if user_signed_in? %>
        <%= drop_down "Signed in as #{current_user.username}" do %>
          <%= menu_item "Profile", edit_user_registration_path %>
          <%= menu_item "Sign out", destroy_user_session_path, method: :delete %>
        <% end %>
      <% else %>
        <%= menu_item "Sign up", new_user_registration_path %>
        <%= menu_item "Sign in", new_user_session_path %>
      <% end %>
    <% end %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <title><%= content_for?(:title) ? yield(:title) : "Smartfarm" %></title>
    <%= csrf_meta_tags %>

    <%= favicon_link_tag 'favicon.ico' %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=AIzaSyAWk3UQFfLP1-q-VrLd46sKcZ-RyYMDfTM&sensor=false&libraries=drawing" %>
    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <%= render partial: 'layouts/navigation' %>

    <div class="container-fluid">

      <%= bootstrap_flash %>
      <%= yield %>

      <footer>
        <p>&copy; Company 2014</p>
      </footer>

    </div> <!-- /container -->

    <%= render "layouts/import_data_dialog" %>

  </body>
</html>